# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title: Romain Vernoux
tagline: About me
description: |
  Head of Labs and Delivery at Zenika.<br>
  IT specialist focused on Software Craftsmanship, Agile and DevOps.<br>
  Travel enthusiast and passionate photographer.<br>
  Alumnus of ENS Paris-Saclay.<br>
url: ''
baseurl: /

author:
  name: Romain Vernoux

paginate: 5

# Custom vars
version: 2.1.0

links:
  twitter: https://twitter.com/RomainVernoux
  github: https://github.com/RomainVernoux
  flickr: https://www.flickr.com/photos/romainvernoux/
